name: ncc
description: Build with @vercel/ncc and commit built files
runs:
  using: node16
  main: dist/index.js
inputs:
  github_token:
    description: required to push the built files
    required: true
  root-directory:
    description: optional sub-directory to use
    required: false
