name: "Setup Yarn"
description: "Sets up JavaScript packages using Yarn"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ inputs.node-version }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.node-version }}-node-modules-
    - name: Cache yarn cache
      id: cache-yarn-cache
      uses: actions/cache@v3
      with:
        path: .yarn/cache
        key: ${{ runner.os }}-${{ inputs.node-version }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.node-version }}-yarn-cache-
    - run: |
        yarn_version=$(yarn --version)
        major_version=$(echo "${yarn_version}" | cut -d. -f1)
        if [[ "${major_version}" != "1" ]]; then
          yarn install --frozen-lockfile --immutable
        else
          yarn install --frozen-lockfile --prefer-offline --immutable
        fi
      shell: bash
inputs:
  node-version:
    description: Version of node to use
    required: false
    default: "18"
branding:
  icon: life-buoy
  color: orange
