name: "Setup NPM"
description: "Sets up JavaScript packages using NPM"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version || (inputs.node-version-file == '' && '18') }}
        node-version-file: ${{ inputs.node-version-file }}
        cache: npm
        cache-dependency-path: "**/package-lock.json"
    - run: npm ci
      shell: bash
inputs:
  node-version:
    description: Version of node to use
    required: false
  node-version-file:
    description: File containing the version of node to use (e.g. .node-version)
    required: false
branding:
  icon: life-buoy
  color: orange
