name: "Setup NPM"
description: "Sets up JavaScript packages using NPM"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.nodeVersion }}
        cache: 'npm'
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ inputs.nodeVersion }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
            ${{ runner.os }}-${{ inputs.nodeVersion }}-node-modules-
    - run: npm i
      shell: bash
inputs:
  nodeVersion:
    required: false
    default: '16'
branding:
  icon: life-buoy
  color: orange
