name: "Setup NPM"
description: "Sets up JavaScript packages using NPM"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: "**/package-lock.json"
    - run: npm ci
      shell: bash
inputs:
  node-version:
    description: Version of node to use
    required: false
    default: "18"
branding:
  icon: life-buoy
  color: orange
